// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pharmaApp3.proto

package pharmaApp3;

public interface APIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ordersConfirmation = 1;</code>
   */
  java.lang.String getOrdersConfirmation();
  /**
   * <code>string ordersConfirmation = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrdersConfirmationBytes();

  /**
   * <code>string orderSummary = 2;</code>
   */
  java.lang.String getOrderSummary();
  /**
   * <code>string orderSummary = 2;</code>
   */
  com.google.protobuf.ByteString
      getOrderSummaryBytes();
}
