// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pharmaApp3.proto

package pharmaApp3;

/**
 * Protobuf type {@code APIResponse}
 */
public  final class APIResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:APIResponse)
    APIResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use APIResponse.newBuilder() to construct.
  private APIResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private APIResponse() {
    ordersConfirmation_ = "";
    orderSummary_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private APIResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            ordersConfirmation_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            orderSummary_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pharmaApp3.Service3OuterClass.internal_static_APIResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pharmaApp3.Service3OuterClass.internal_static_APIResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pharmaApp3.APIResponse.class, pharmaApp3.APIResponse.Builder.class);
  }

  public static final int ORDERSCONFIRMATION_FIELD_NUMBER = 1;
  private volatile java.lang.Object ordersConfirmation_;
  /**
   * <code>string ordersConfirmation = 1;</code>
   */
  public java.lang.String getOrdersConfirmation() {
    java.lang.Object ref = ordersConfirmation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ordersConfirmation_ = s;
      return s;
    }
  }
  /**
   * <code>string ordersConfirmation = 1;</code>
   */
  public com.google.protobuf.ByteString
      getOrdersConfirmationBytes() {
    java.lang.Object ref = ordersConfirmation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ordersConfirmation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDERSUMMARY_FIELD_NUMBER = 2;
  private volatile java.lang.Object orderSummary_;
  /**
   * <code>string orderSummary = 2;</code>
   */
  public java.lang.String getOrderSummary() {
    java.lang.Object ref = orderSummary_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orderSummary_ = s;
      return s;
    }
  }
  /**
   * <code>string orderSummary = 2;</code>
   */
  public com.google.protobuf.ByteString
      getOrderSummaryBytes() {
    java.lang.Object ref = orderSummary_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orderSummary_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOrdersConfirmationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ordersConfirmation_);
    }
    if (!getOrderSummaryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, orderSummary_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOrdersConfirmationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ordersConfirmation_);
    }
    if (!getOrderSummaryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, orderSummary_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pharmaApp3.APIResponse)) {
      return super.equals(obj);
    }
    pharmaApp3.APIResponse other = (pharmaApp3.APIResponse) obj;

    boolean result = true;
    result = result && getOrdersConfirmation()
        .equals(other.getOrdersConfirmation());
    result = result && getOrderSummary()
        .equals(other.getOrderSummary());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ORDERSCONFIRMATION_FIELD_NUMBER;
    hash = (53 * hash) + getOrdersConfirmation().hashCode();
    hash = (37 * hash) + ORDERSUMMARY_FIELD_NUMBER;
    hash = (53 * hash) + getOrderSummary().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pharmaApp3.APIResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pharmaApp3.APIResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pharmaApp3.APIResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pharmaApp3.APIResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pharmaApp3.APIResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pharmaApp3.APIResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pharmaApp3.APIResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pharmaApp3.APIResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static pharmaApp3.APIResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static pharmaApp3.APIResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pharmaApp3.APIResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pharmaApp3.APIResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pharmaApp3.APIResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code APIResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:APIResponse)
      pharmaApp3.APIResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pharmaApp3.Service3OuterClass.internal_static_APIResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pharmaApp3.Service3OuterClass.internal_static_APIResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pharmaApp3.APIResponse.class, pharmaApp3.APIResponse.Builder.class);
    }

    // Construct using pharmaApp3.APIResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ordersConfirmation_ = "";

      orderSummary_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pharmaApp3.Service3OuterClass.internal_static_APIResponse_descriptor;
    }

    @java.lang.Override
    public pharmaApp3.APIResponse getDefaultInstanceForType() {
      return pharmaApp3.APIResponse.getDefaultInstance();
    }

    @java.lang.Override
    public pharmaApp3.APIResponse build() {
      pharmaApp3.APIResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public pharmaApp3.APIResponse buildPartial() {
      pharmaApp3.APIResponse result = new pharmaApp3.APIResponse(this);
      result.ordersConfirmation_ = ordersConfirmation_;
      result.orderSummary_ = orderSummary_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pharmaApp3.APIResponse) {
        return mergeFrom((pharmaApp3.APIResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pharmaApp3.APIResponse other) {
      if (other == pharmaApp3.APIResponse.getDefaultInstance()) return this;
      if (!other.getOrdersConfirmation().isEmpty()) {
        ordersConfirmation_ = other.ordersConfirmation_;
        onChanged();
      }
      if (!other.getOrderSummary().isEmpty()) {
        orderSummary_ = other.orderSummary_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      pharmaApp3.APIResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (pharmaApp3.APIResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object ordersConfirmation_ = "";
    /**
     * <code>string ordersConfirmation = 1;</code>
     */
    public java.lang.String getOrdersConfirmation() {
      java.lang.Object ref = ordersConfirmation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ordersConfirmation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ordersConfirmation = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOrdersConfirmationBytes() {
      java.lang.Object ref = ordersConfirmation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ordersConfirmation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ordersConfirmation = 1;</code>
     */
    public Builder setOrdersConfirmation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ordersConfirmation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ordersConfirmation = 1;</code>
     */
    public Builder clearOrdersConfirmation() {
      
      ordersConfirmation_ = getDefaultInstance().getOrdersConfirmation();
      onChanged();
      return this;
    }
    /**
     * <code>string ordersConfirmation = 1;</code>
     */
    public Builder setOrdersConfirmationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ordersConfirmation_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object orderSummary_ = "";
    /**
     * <code>string orderSummary = 2;</code>
     */
    public java.lang.String getOrderSummary() {
      java.lang.Object ref = orderSummary_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderSummary_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string orderSummary = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOrderSummaryBytes() {
      java.lang.Object ref = orderSummary_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderSummary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string orderSummary = 2;</code>
     */
    public Builder setOrderSummary(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      orderSummary_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string orderSummary = 2;</code>
     */
    public Builder clearOrderSummary() {
      
      orderSummary_ = getDefaultInstance().getOrderSummary();
      onChanged();
      return this;
    }
    /**
     * <code>string orderSummary = 2;</code>
     */
    public Builder setOrderSummaryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      orderSummary_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:APIResponse)
  }

  // @@protoc_insertion_point(class_scope:APIResponse)
  private static final pharmaApp3.APIResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pharmaApp3.APIResponse();
  }

  public static pharmaApp3.APIResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<APIResponse>
      PARSER = new com.google.protobuf.AbstractParser<APIResponse>() {
    @java.lang.Override
    public APIResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new APIResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<APIResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<APIResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public pharmaApp3.APIResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

