// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pharmaApp3.proto

package pharmaApp3;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestStatus1 = 1;</code>
   */
  java.lang.String getRequestStatus1();
  /**
   * <code>string requestStatus1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestStatus1Bytes();

  /**
   * <code>string requestStatus2 = 2;</code>
   */
  java.lang.String getRequestStatus2();
  /**
   * <code>string requestStatus2 = 2;</code>
   */
  com.google.protobuf.ByteString
      getRequestStatus2Bytes();

  /**
   * <code>string requestStatus3 = 3;</code>
   */
  java.lang.String getRequestStatus3();
  /**
   * <code>string requestStatus3 = 3;</code>
   */
  com.google.protobuf.ByteString
      getRequestStatus3Bytes();

  /**
   * <code>string requestStatus4 = 4;</code>
   */
  java.lang.String getRequestStatus4();
  /**
   * <code>string requestStatus4 = 4;</code>
   */
  com.google.protobuf.ByteString
      getRequestStatus4Bytes();

  /**
   * <code>string requestStatus5 = 5;</code>
   */
  java.lang.String getRequestStatus5();
  /**
   * <code>string requestStatus5 = 5;</code>
   */
  com.google.protobuf.ByteString
      getRequestStatus5Bytes();

  /**
   * <code>string requestStatus6 = 6;</code>
   */
  java.lang.String getRequestStatus6();
  /**
   * <code>string requestStatus6 = 6;</code>
   */
  com.google.protobuf.ByteString
      getRequestStatus6Bytes();
}
