// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pharmaApp3.proto

package pharmaApp3;

/**
 * Protobuf type {@code OrderRequest}
 */
public  final class OrderRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:OrderRequest)
    OrderRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderRequest.newBuilder() to construct.
  private OrderRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderRequest() {
    requestStatus1_ = "";
    requestStatus2_ = "";
    requestStatus3_ = "";
    requestStatus4_ = "";
    requestStatus5_ = "";
    requestStatus6_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OrderRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            requestStatus1_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            requestStatus2_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            requestStatus3_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            requestStatus4_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            requestStatus5_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            requestStatus6_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pharmaApp3.Service3OuterClass.internal_static_OrderRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pharmaApp3.Service3OuterClass.internal_static_OrderRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pharmaApp3.OrderRequest.class, pharmaApp3.OrderRequest.Builder.class);
  }

  public static final int REQUESTSTATUS1_FIELD_NUMBER = 1;
  private volatile java.lang.Object requestStatus1_;
  /**
   * <code>string requestStatus1 = 1;</code>
   */
  public java.lang.String getRequestStatus1() {
    java.lang.Object ref = requestStatus1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestStatus1_ = s;
      return s;
    }
  }
  /**
   * <code>string requestStatus1 = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRequestStatus1Bytes() {
    java.lang.Object ref = requestStatus1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestStatus1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUESTSTATUS2_FIELD_NUMBER = 2;
  private volatile java.lang.Object requestStatus2_;
  /**
   * <code>string requestStatus2 = 2;</code>
   */
  public java.lang.String getRequestStatus2() {
    java.lang.Object ref = requestStatus2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestStatus2_ = s;
      return s;
    }
  }
  /**
   * <code>string requestStatus2 = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRequestStatus2Bytes() {
    java.lang.Object ref = requestStatus2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestStatus2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUESTSTATUS3_FIELD_NUMBER = 3;
  private volatile java.lang.Object requestStatus3_;
  /**
   * <code>string requestStatus3 = 3;</code>
   */
  public java.lang.String getRequestStatus3() {
    java.lang.Object ref = requestStatus3_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestStatus3_ = s;
      return s;
    }
  }
  /**
   * <code>string requestStatus3 = 3;</code>
   */
  public com.google.protobuf.ByteString
      getRequestStatus3Bytes() {
    java.lang.Object ref = requestStatus3_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestStatus3_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUESTSTATUS4_FIELD_NUMBER = 4;
  private volatile java.lang.Object requestStatus4_;
  /**
   * <code>string requestStatus4 = 4;</code>
   */
  public java.lang.String getRequestStatus4() {
    java.lang.Object ref = requestStatus4_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestStatus4_ = s;
      return s;
    }
  }
  /**
   * <code>string requestStatus4 = 4;</code>
   */
  public com.google.protobuf.ByteString
      getRequestStatus4Bytes() {
    java.lang.Object ref = requestStatus4_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestStatus4_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUESTSTATUS5_FIELD_NUMBER = 5;
  private volatile java.lang.Object requestStatus5_;
  /**
   * <code>string requestStatus5 = 5;</code>
   */
  public java.lang.String getRequestStatus5() {
    java.lang.Object ref = requestStatus5_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestStatus5_ = s;
      return s;
    }
  }
  /**
   * <code>string requestStatus5 = 5;</code>
   */
  public com.google.protobuf.ByteString
      getRequestStatus5Bytes() {
    java.lang.Object ref = requestStatus5_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestStatus5_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUESTSTATUS6_FIELD_NUMBER = 6;
  private volatile java.lang.Object requestStatus6_;
  /**
   * <code>string requestStatus6 = 6;</code>
   */
  public java.lang.String getRequestStatus6() {
    java.lang.Object ref = requestStatus6_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestStatus6_ = s;
      return s;
    }
  }
  /**
   * <code>string requestStatus6 = 6;</code>
   */
  public com.google.protobuf.ByteString
      getRequestStatus6Bytes() {
    java.lang.Object ref = requestStatus6_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestStatus6_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRequestStatus1Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestStatus1_);
    }
    if (!getRequestStatus2Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, requestStatus2_);
    }
    if (!getRequestStatus3Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, requestStatus3_);
    }
    if (!getRequestStatus4Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, requestStatus4_);
    }
    if (!getRequestStatus5Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, requestStatus5_);
    }
    if (!getRequestStatus6Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, requestStatus6_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRequestStatus1Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestStatus1_);
    }
    if (!getRequestStatus2Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, requestStatus2_);
    }
    if (!getRequestStatus3Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, requestStatus3_);
    }
    if (!getRequestStatus4Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, requestStatus4_);
    }
    if (!getRequestStatus5Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, requestStatus5_);
    }
    if (!getRequestStatus6Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, requestStatus6_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pharmaApp3.OrderRequest)) {
      return super.equals(obj);
    }
    pharmaApp3.OrderRequest other = (pharmaApp3.OrderRequest) obj;

    boolean result = true;
    result = result && getRequestStatus1()
        .equals(other.getRequestStatus1());
    result = result && getRequestStatus2()
        .equals(other.getRequestStatus2());
    result = result && getRequestStatus3()
        .equals(other.getRequestStatus3());
    result = result && getRequestStatus4()
        .equals(other.getRequestStatus4());
    result = result && getRequestStatus5()
        .equals(other.getRequestStatus5());
    result = result && getRequestStatus6()
        .equals(other.getRequestStatus6());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUESTSTATUS1_FIELD_NUMBER;
    hash = (53 * hash) + getRequestStatus1().hashCode();
    hash = (37 * hash) + REQUESTSTATUS2_FIELD_NUMBER;
    hash = (53 * hash) + getRequestStatus2().hashCode();
    hash = (37 * hash) + REQUESTSTATUS3_FIELD_NUMBER;
    hash = (53 * hash) + getRequestStatus3().hashCode();
    hash = (37 * hash) + REQUESTSTATUS4_FIELD_NUMBER;
    hash = (53 * hash) + getRequestStatus4().hashCode();
    hash = (37 * hash) + REQUESTSTATUS5_FIELD_NUMBER;
    hash = (53 * hash) + getRequestStatus5().hashCode();
    hash = (37 * hash) + REQUESTSTATUS6_FIELD_NUMBER;
    hash = (53 * hash) + getRequestStatus6().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pharmaApp3.OrderRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pharmaApp3.OrderRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pharmaApp3.OrderRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pharmaApp3.OrderRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pharmaApp3.OrderRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pharmaApp3.OrderRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pharmaApp3.OrderRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pharmaApp3.OrderRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static pharmaApp3.OrderRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static pharmaApp3.OrderRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pharmaApp3.OrderRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pharmaApp3.OrderRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pharmaApp3.OrderRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code OrderRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OrderRequest)
      pharmaApp3.OrderRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pharmaApp3.Service3OuterClass.internal_static_OrderRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pharmaApp3.Service3OuterClass.internal_static_OrderRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pharmaApp3.OrderRequest.class, pharmaApp3.OrderRequest.Builder.class);
    }

    // Construct using pharmaApp3.OrderRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestStatus1_ = "";

      requestStatus2_ = "";

      requestStatus3_ = "";

      requestStatus4_ = "";

      requestStatus5_ = "";

      requestStatus6_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pharmaApp3.Service3OuterClass.internal_static_OrderRequest_descriptor;
    }

    @java.lang.Override
    public pharmaApp3.OrderRequest getDefaultInstanceForType() {
      return pharmaApp3.OrderRequest.getDefaultInstance();
    }

    @java.lang.Override
    public pharmaApp3.OrderRequest build() {
      pharmaApp3.OrderRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public pharmaApp3.OrderRequest buildPartial() {
      pharmaApp3.OrderRequest result = new pharmaApp3.OrderRequest(this);
      result.requestStatus1_ = requestStatus1_;
      result.requestStatus2_ = requestStatus2_;
      result.requestStatus3_ = requestStatus3_;
      result.requestStatus4_ = requestStatus4_;
      result.requestStatus5_ = requestStatus5_;
      result.requestStatus6_ = requestStatus6_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pharmaApp3.OrderRequest) {
        return mergeFrom((pharmaApp3.OrderRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pharmaApp3.OrderRequest other) {
      if (other == pharmaApp3.OrderRequest.getDefaultInstance()) return this;
      if (!other.getRequestStatus1().isEmpty()) {
        requestStatus1_ = other.requestStatus1_;
        onChanged();
      }
      if (!other.getRequestStatus2().isEmpty()) {
        requestStatus2_ = other.requestStatus2_;
        onChanged();
      }
      if (!other.getRequestStatus3().isEmpty()) {
        requestStatus3_ = other.requestStatus3_;
        onChanged();
      }
      if (!other.getRequestStatus4().isEmpty()) {
        requestStatus4_ = other.requestStatus4_;
        onChanged();
      }
      if (!other.getRequestStatus5().isEmpty()) {
        requestStatus5_ = other.requestStatus5_;
        onChanged();
      }
      if (!other.getRequestStatus6().isEmpty()) {
        requestStatus6_ = other.requestStatus6_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      pharmaApp3.OrderRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (pharmaApp3.OrderRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object requestStatus1_ = "";
    /**
     * <code>string requestStatus1 = 1;</code>
     */
    public java.lang.String getRequestStatus1() {
      java.lang.Object ref = requestStatus1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestStatus1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string requestStatus1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestStatus1Bytes() {
      java.lang.Object ref = requestStatus1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestStatus1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string requestStatus1 = 1;</code>
     */
    public Builder setRequestStatus1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestStatus1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string requestStatus1 = 1;</code>
     */
    public Builder clearRequestStatus1() {
      
      requestStatus1_ = getDefaultInstance().getRequestStatus1();
      onChanged();
      return this;
    }
    /**
     * <code>string requestStatus1 = 1;</code>
     */
    public Builder setRequestStatus1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestStatus1_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object requestStatus2_ = "";
    /**
     * <code>string requestStatus2 = 2;</code>
     */
    public java.lang.String getRequestStatus2() {
      java.lang.Object ref = requestStatus2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestStatus2_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string requestStatus2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRequestStatus2Bytes() {
      java.lang.Object ref = requestStatus2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestStatus2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string requestStatus2 = 2;</code>
     */
    public Builder setRequestStatus2(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestStatus2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string requestStatus2 = 2;</code>
     */
    public Builder clearRequestStatus2() {
      
      requestStatus2_ = getDefaultInstance().getRequestStatus2();
      onChanged();
      return this;
    }
    /**
     * <code>string requestStatus2 = 2;</code>
     */
    public Builder setRequestStatus2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestStatus2_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object requestStatus3_ = "";
    /**
     * <code>string requestStatus3 = 3;</code>
     */
    public java.lang.String getRequestStatus3() {
      java.lang.Object ref = requestStatus3_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestStatus3_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string requestStatus3 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRequestStatus3Bytes() {
      java.lang.Object ref = requestStatus3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestStatus3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string requestStatus3 = 3;</code>
     */
    public Builder setRequestStatus3(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestStatus3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string requestStatus3 = 3;</code>
     */
    public Builder clearRequestStatus3() {
      
      requestStatus3_ = getDefaultInstance().getRequestStatus3();
      onChanged();
      return this;
    }
    /**
     * <code>string requestStatus3 = 3;</code>
     */
    public Builder setRequestStatus3Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestStatus3_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object requestStatus4_ = "";
    /**
     * <code>string requestStatus4 = 4;</code>
     */
    public java.lang.String getRequestStatus4() {
      java.lang.Object ref = requestStatus4_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestStatus4_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string requestStatus4 = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRequestStatus4Bytes() {
      java.lang.Object ref = requestStatus4_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestStatus4_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string requestStatus4 = 4;</code>
     */
    public Builder setRequestStatus4(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestStatus4_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string requestStatus4 = 4;</code>
     */
    public Builder clearRequestStatus4() {
      
      requestStatus4_ = getDefaultInstance().getRequestStatus4();
      onChanged();
      return this;
    }
    /**
     * <code>string requestStatus4 = 4;</code>
     */
    public Builder setRequestStatus4Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestStatus4_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object requestStatus5_ = "";
    /**
     * <code>string requestStatus5 = 5;</code>
     */
    public java.lang.String getRequestStatus5() {
      java.lang.Object ref = requestStatus5_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestStatus5_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string requestStatus5 = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRequestStatus5Bytes() {
      java.lang.Object ref = requestStatus5_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestStatus5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string requestStatus5 = 5;</code>
     */
    public Builder setRequestStatus5(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestStatus5_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string requestStatus5 = 5;</code>
     */
    public Builder clearRequestStatus5() {
      
      requestStatus5_ = getDefaultInstance().getRequestStatus5();
      onChanged();
      return this;
    }
    /**
     * <code>string requestStatus5 = 5;</code>
     */
    public Builder setRequestStatus5Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestStatus5_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object requestStatus6_ = "";
    /**
     * <code>string requestStatus6 = 6;</code>
     */
    public java.lang.String getRequestStatus6() {
      java.lang.Object ref = requestStatus6_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestStatus6_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string requestStatus6 = 6;</code>
     */
    public com.google.protobuf.ByteString
        getRequestStatus6Bytes() {
      java.lang.Object ref = requestStatus6_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestStatus6_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string requestStatus6 = 6;</code>
     */
    public Builder setRequestStatus6(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestStatus6_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string requestStatus6 = 6;</code>
     */
    public Builder clearRequestStatus6() {
      
      requestStatus6_ = getDefaultInstance().getRequestStatus6();
      onChanged();
      return this;
    }
    /**
     * <code>string requestStatus6 = 6;</code>
     */
    public Builder setRequestStatus6Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestStatus6_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:OrderRequest)
  }

  // @@protoc_insertion_point(class_scope:OrderRequest)
  private static final pharmaApp3.OrderRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pharmaApp3.OrderRequest();
  }

  public static pharmaApp3.OrderRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderRequest>
      PARSER = new com.google.protobuf.AbstractParser<OrderRequest>() {
    @java.lang.Override
    public OrderRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OrderRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public pharmaApp3.OrderRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

