// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pharmaApp3.proto

package pharmaApp3;

public final class Service3OuterClass {
  private Service3OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APIResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020pharmaApp3.proto\"\236\001\n\014OrderRequest\022\026\n\016r" +
      "equestStatus1\030\001 \001(\t\022\026\n\016requestStatus2\030\002 " +
      "\001(\t\022\026\n\016requestStatus3\030\003 \001(\t\022\026\n\016requestSt" +
      "atus4\030\004 \001(\t\022\026\n\016requestStatus5\030\005 \001(\t\022\026\n\016r" +
      "equestStatus6\030\006 \001(\t\"?\n\013APIResponse\022\032\n\022or" +
      "dersConfirmation\030\001 \001(\t\022\024\n\014orderSummary\030\002" +
      " \001(\t2=\n\010Service3\0221\n\014orderRequest\022\r.Order" +
      "Request\032\014.APIResponse\"\000(\0010\001B\"\n\npharmaApp" +
      "3B\022Service3OuterClassP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderRequest_descriptor,
        new java.lang.String[] { "RequestStatus1", "RequestStatus2", "RequestStatus3", "RequestStatus4", "RequestStatus5", "RequestStatus6", });
    internal_static_APIResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_APIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APIResponse_descriptor,
        new java.lang.String[] { "OrdersConfirmation", "OrderSummary", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
