// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pharmaApp1.proto

package pharmaApp1;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
