// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pharmaApp2.proto

package pharmaApp2;

public interface APIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 responseTime1 = 1;</code>
   */
  int getResponseTime1();

  /**
   * <code>int32 responseTime2 = 2;</code>
   */
  int getResponseTime2();

  /**
   * <code>int32 responseTime3 = 3;</code>
   */
  int getResponseTime3();

  /**
   * <code>int32 responseTime4 = 4;</code>
   */
  int getResponseTime4();

  /**
   * <code>int32 responseTime5 = 5;</code>
   */
  int getResponseTime5();

  /**
   * <code>int32 responseTime6 = 6;</code>
   */
  int getResponseTime6();
}
