// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pharmaApp2.proto

package pharmaApp2;

/**
 * Protobuf type {@code APIResponse}
 */
public  final class APIResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:APIResponse)
    APIResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use APIResponse.newBuilder() to construct.
  private APIResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private APIResponse() {
    responseTime1_ = 0;
    responseTime2_ = 0;
    responseTime3_ = 0;
    responseTime4_ = 0;
    responseTime5_ = 0;
    responseTime6_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private APIResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            responseTime1_ = input.readInt32();
            break;
          }
          case 16: {

            responseTime2_ = input.readInt32();
            break;
          }
          case 24: {

            responseTime3_ = input.readInt32();
            break;
          }
          case 32: {

            responseTime4_ = input.readInt32();
            break;
          }
          case 40: {

            responseTime5_ = input.readInt32();
            break;
          }
          case 48: {

            responseTime6_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pharmaApp2.Service2OuterClass.internal_static_APIResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pharmaApp2.Service2OuterClass.internal_static_APIResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            pharmaApp2.APIResponse.class, pharmaApp2.APIResponse.Builder.class);
  }

  public static final int RESPONSETIME1_FIELD_NUMBER = 1;
  private int responseTime1_;
  /**
   * <code>int32 responseTime1 = 1;</code>
   */
  public int getResponseTime1() {
    return responseTime1_;
  }

  public static final int RESPONSETIME2_FIELD_NUMBER = 2;
  private int responseTime2_;
  /**
   * <code>int32 responseTime2 = 2;</code>
   */
  public int getResponseTime2() {
    return responseTime2_;
  }

  public static final int RESPONSETIME3_FIELD_NUMBER = 3;
  private int responseTime3_;
  /**
   * <code>int32 responseTime3 = 3;</code>
   */
  public int getResponseTime3() {
    return responseTime3_;
  }

  public static final int RESPONSETIME4_FIELD_NUMBER = 4;
  private int responseTime4_;
  /**
   * <code>int32 responseTime4 = 4;</code>
   */
  public int getResponseTime4() {
    return responseTime4_;
  }

  public static final int RESPONSETIME5_FIELD_NUMBER = 5;
  private int responseTime5_;
  /**
   * <code>int32 responseTime5 = 5;</code>
   */
  public int getResponseTime5() {
    return responseTime5_;
  }

  public static final int RESPONSETIME6_FIELD_NUMBER = 6;
  private int responseTime6_;
  /**
   * <code>int32 responseTime6 = 6;</code>
   */
  public int getResponseTime6() {
    return responseTime6_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (responseTime1_ != 0) {
      output.writeInt32(1, responseTime1_);
    }
    if (responseTime2_ != 0) {
      output.writeInt32(2, responseTime2_);
    }
    if (responseTime3_ != 0) {
      output.writeInt32(3, responseTime3_);
    }
    if (responseTime4_ != 0) {
      output.writeInt32(4, responseTime4_);
    }
    if (responseTime5_ != 0) {
      output.writeInt32(5, responseTime5_);
    }
    if (responseTime6_ != 0) {
      output.writeInt32(6, responseTime6_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (responseTime1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, responseTime1_);
    }
    if (responseTime2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, responseTime2_);
    }
    if (responseTime3_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, responseTime3_);
    }
    if (responseTime4_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, responseTime4_);
    }
    if (responseTime5_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, responseTime5_);
    }
    if (responseTime6_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, responseTime6_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof pharmaApp2.APIResponse)) {
      return super.equals(obj);
    }
    pharmaApp2.APIResponse other = (pharmaApp2.APIResponse) obj;

    boolean result = true;
    result = result && (getResponseTime1()
        == other.getResponseTime1());
    result = result && (getResponseTime2()
        == other.getResponseTime2());
    result = result && (getResponseTime3()
        == other.getResponseTime3());
    result = result && (getResponseTime4()
        == other.getResponseTime4());
    result = result && (getResponseTime5()
        == other.getResponseTime5());
    result = result && (getResponseTime6()
        == other.getResponseTime6());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESPONSETIME1_FIELD_NUMBER;
    hash = (53 * hash) + getResponseTime1();
    hash = (37 * hash) + RESPONSETIME2_FIELD_NUMBER;
    hash = (53 * hash) + getResponseTime2();
    hash = (37 * hash) + RESPONSETIME3_FIELD_NUMBER;
    hash = (53 * hash) + getResponseTime3();
    hash = (37 * hash) + RESPONSETIME4_FIELD_NUMBER;
    hash = (53 * hash) + getResponseTime4();
    hash = (37 * hash) + RESPONSETIME5_FIELD_NUMBER;
    hash = (53 * hash) + getResponseTime5();
    hash = (37 * hash) + RESPONSETIME6_FIELD_NUMBER;
    hash = (53 * hash) + getResponseTime6();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static pharmaApp2.APIResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pharmaApp2.APIResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pharmaApp2.APIResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pharmaApp2.APIResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pharmaApp2.APIResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static pharmaApp2.APIResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static pharmaApp2.APIResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pharmaApp2.APIResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static pharmaApp2.APIResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static pharmaApp2.APIResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static pharmaApp2.APIResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static pharmaApp2.APIResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pharmaApp2.APIResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code APIResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:APIResponse)
      pharmaApp2.APIResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pharmaApp2.Service2OuterClass.internal_static_APIResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pharmaApp2.Service2OuterClass.internal_static_APIResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pharmaApp2.APIResponse.class, pharmaApp2.APIResponse.Builder.class);
    }

    // Construct using pharmaApp2.APIResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      responseTime1_ = 0;

      responseTime2_ = 0;

      responseTime3_ = 0;

      responseTime4_ = 0;

      responseTime5_ = 0;

      responseTime6_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pharmaApp2.Service2OuterClass.internal_static_APIResponse_descriptor;
    }

    @java.lang.Override
    public pharmaApp2.APIResponse getDefaultInstanceForType() {
      return pharmaApp2.APIResponse.getDefaultInstance();
    }

    @java.lang.Override
    public pharmaApp2.APIResponse build() {
      pharmaApp2.APIResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public pharmaApp2.APIResponse buildPartial() {
      pharmaApp2.APIResponse result = new pharmaApp2.APIResponse(this);
      result.responseTime1_ = responseTime1_;
      result.responseTime2_ = responseTime2_;
      result.responseTime3_ = responseTime3_;
      result.responseTime4_ = responseTime4_;
      result.responseTime5_ = responseTime5_;
      result.responseTime6_ = responseTime6_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof pharmaApp2.APIResponse) {
        return mergeFrom((pharmaApp2.APIResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(pharmaApp2.APIResponse other) {
      if (other == pharmaApp2.APIResponse.getDefaultInstance()) return this;
      if (other.getResponseTime1() != 0) {
        setResponseTime1(other.getResponseTime1());
      }
      if (other.getResponseTime2() != 0) {
        setResponseTime2(other.getResponseTime2());
      }
      if (other.getResponseTime3() != 0) {
        setResponseTime3(other.getResponseTime3());
      }
      if (other.getResponseTime4() != 0) {
        setResponseTime4(other.getResponseTime4());
      }
      if (other.getResponseTime5() != 0) {
        setResponseTime5(other.getResponseTime5());
      }
      if (other.getResponseTime6() != 0) {
        setResponseTime6(other.getResponseTime6());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      pharmaApp2.APIResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (pharmaApp2.APIResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int responseTime1_ ;
    /**
     * <code>int32 responseTime1 = 1;</code>
     */
    public int getResponseTime1() {
      return responseTime1_;
    }
    /**
     * <code>int32 responseTime1 = 1;</code>
     */
    public Builder setResponseTime1(int value) {
      
      responseTime1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 responseTime1 = 1;</code>
     */
    public Builder clearResponseTime1() {
      
      responseTime1_ = 0;
      onChanged();
      return this;
    }

    private int responseTime2_ ;
    /**
     * <code>int32 responseTime2 = 2;</code>
     */
    public int getResponseTime2() {
      return responseTime2_;
    }
    /**
     * <code>int32 responseTime2 = 2;</code>
     */
    public Builder setResponseTime2(int value) {
      
      responseTime2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 responseTime2 = 2;</code>
     */
    public Builder clearResponseTime2() {
      
      responseTime2_ = 0;
      onChanged();
      return this;
    }

    private int responseTime3_ ;
    /**
     * <code>int32 responseTime3 = 3;</code>
     */
    public int getResponseTime3() {
      return responseTime3_;
    }
    /**
     * <code>int32 responseTime3 = 3;</code>
     */
    public Builder setResponseTime3(int value) {
      
      responseTime3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 responseTime3 = 3;</code>
     */
    public Builder clearResponseTime3() {
      
      responseTime3_ = 0;
      onChanged();
      return this;
    }

    private int responseTime4_ ;
    /**
     * <code>int32 responseTime4 = 4;</code>
     */
    public int getResponseTime4() {
      return responseTime4_;
    }
    /**
     * <code>int32 responseTime4 = 4;</code>
     */
    public Builder setResponseTime4(int value) {
      
      responseTime4_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 responseTime4 = 4;</code>
     */
    public Builder clearResponseTime4() {
      
      responseTime4_ = 0;
      onChanged();
      return this;
    }

    private int responseTime5_ ;
    /**
     * <code>int32 responseTime5 = 5;</code>
     */
    public int getResponseTime5() {
      return responseTime5_;
    }
    /**
     * <code>int32 responseTime5 = 5;</code>
     */
    public Builder setResponseTime5(int value) {
      
      responseTime5_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 responseTime5 = 5;</code>
     */
    public Builder clearResponseTime5() {
      
      responseTime5_ = 0;
      onChanged();
      return this;
    }

    private int responseTime6_ ;
    /**
     * <code>int32 responseTime6 = 6;</code>
     */
    public int getResponseTime6() {
      return responseTime6_;
    }
    /**
     * <code>int32 responseTime6 = 6;</code>
     */
    public Builder setResponseTime6(int value) {
      
      responseTime6_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 responseTime6 = 6;</code>
     */
    public Builder clearResponseTime6() {
      
      responseTime6_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:APIResponse)
  }

  // @@protoc_insertion_point(class_scope:APIResponse)
  private static final pharmaApp2.APIResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new pharmaApp2.APIResponse();
  }

  public static pharmaApp2.APIResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<APIResponse>
      PARSER = new com.google.protobuf.AbstractParser<APIResponse>() {
    @java.lang.Override
    public APIResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new APIResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<APIResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<APIResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public pharmaApp2.APIResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

