// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pharmaApp2.proto

package pharmaApp2;

public final class Service2OuterClass {
  private Service2OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TimeUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TimeUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APIResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020pharmaApp2.proto\"(\n\021TimeUpdateRequest\022" +
      "\023\n\013requestTime\030\001 \001(\t\"\227\001\n\013APIResponse\022\025\n\r" +
      "responseTime1\030\001 \001(\005\022\025\n\rresponseTime2\030\002 \001" +
      "(\005\022\025\n\rresponseTime3\030\003 \001(\005\022\025\n\rresponseTim" +
      "e4\030\004 \001(\005\022\025\n\rresponseTime5\030\005 \001(\005\022\025\n\rrespo" +
      "nseTime6\030\006 \001(\0052C\n\010Service2\0227\n\021ArrivalTim" +
      "eUpdate\022\022.TimeUpdateRequest\032\014.APIRespons" +
      "e0\001B\"\n\npharmaApp2B\022Service2OuterClassP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TimeUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TimeUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TimeUpdateRequest_descriptor,
        new java.lang.String[] { "RequestTime", });
    internal_static_APIResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_APIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APIResponse_descriptor,
        new java.lang.String[] { "ResponseTime1", "ResponseTime2", "ResponseTime3", "ResponseTime4", "ResponseTime5", "ResponseTime6", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
