// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pharmaApp2.proto

package pharmaApp2;

public interface TimeUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TimeUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestTime = 1;</code>
   */
  java.lang.String getRequestTime();
  /**
   * <code>string requestTime = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestTimeBytes();
}
